name: Test
on: [push]
jobs:
    run_tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: Install python 3.10
        - uses: actions/setup-python@v1
          with:
            python-version: '3.10'
        - name: Install requirements
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Run tests
          run: |
            pytest